version: '3.4'

services:
  aviocompanyapi:
    image: ${DOCKER_REGISTRY-}aviocompanyapi
    build:
      context: .
      dockerfile: AvioCompanyAPI/Dockerfile
    depends_on:
      - mysql-server


  rentcompanyapi:
    image: ${DOCKER_REGISTRY-}rentcompanyapi
    build:
      context: .
      dockerfile: RentCompanyAPI/Dockerfile
    depends_on:
      - mysql-server


  mysql-server:
    image: mysql/mysql-server:5.6
    ports:
      - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: "RootPassword!123"
        MYSQL_USER: "user"
        MYSQL_PASSWORD: "Password!123"
    volumes:
      - database:/var/lib/mysql

volumes:
  database:

